// DB hoạt động — kcal = MET × kg × giờ
const ACT_DB = [
  {id:'act_001', name:'Ngủ', met:0.95, icon:'⭐'},
  {id:'act_002', name:'Ngồi thiền hoặc tập thở sâu', met:1, icon:'·'},
  {id:'act_003', name:'Nằm nghỉ ngơi, xem TV', met:1.3, icon:'⭐'},
  {id:'act_004', name:'Ngồi đọc sách, báo', met:1.3, icon:'·'},
  {id:'act_005', name:'Ngồi viết nhật ký, ghi chép', met:1.3, icon:'·'},
  {id:'act_006', name:'Đứng xếp hàng chờ đợi', met:1.3, icon:'·'},
  {id:'act_007', name:'Ăn uống (ngồi tại bàn)', met:1.5, icon:'⭐'},
  {id:'act_008', name:'Ngồi chơi boardgame, đánh bài', met:1.5, icon:'·'},
  {id:'act_009', name:'Đứng nói chuyện, thảo luận', met:1.8, icon:'·'},
  {id:'act_010', name:'Sấy tóc, tạo kiểu tóc', met:1.8, icon:'·'},
  {id:'act_011', name:'Tắm rửa, vệ sinh cá nhân', met:2, icon:'⭐'},
  {id:'act_012', name:'Chơi đàn guitar, piano (ngồi)', met:2, icon:'·'},
  {id:'act_013', name:'Mặc quần áo, sửa soạn', met:2.5, icon:'·'},
  {id:'act_014', name:'Hát karaoke (đứng)', met:2.5, icon:'·'},
  {id:'act_015', name:'Chơi trống (ngồi chơi nhạc cụ sôi động)', met:3.8, icon:'·'},
  {id:'act_016', name:'Ngồi làm việc máy tính / Lập trình', met:1.5, icon:'⭐'},
  {id:'act_017', name:'Ngồi họp trực tiếp, thảo luận', met:1.5, icon:'⭐'},
  {id:'act_018', name:'Ngồi họp online qua Zoom, Teams', met:1.5, icon:'⭐'},
  {id:'act_019', name:'Ngồi vẽ máy tính, thiết kế đồ họa bằng wacom', met:1.5, icon:'·'},
  {id:'act_020', name:'Đứng làm việc tại bàn nâng hạ', met:1.8, icon:'·'},
  {id:'act_021', name:'Gửi nhận tài liệu, in ấn, photo văn bản', met:1.8, icon:'·'},
  {id:'act_022', name:'Đi lại nhẹ nhàng đổi phòng họp / Thư giãn Pomodoro', met:2, icon:'⭐'},
  {id:'act_023', name:'Pha cafe, trà thủ công tại góc làm việc', met:2, icon:'⭐'},
  {id:'act_024', name:'Dọn dẹp, setup bàn làm việc cá nhân', met:2, icon:'⭐'},
  {id:'act_025', name:'Sắp xếp hồ sơ, lưu trữ tủ tài liệu', met:2.3, icon:'·'},
  {id:'act_026', name:'Đứng thuyết trình, tổ chức workshop', met:2.5, icon:'·'},
  {id:'act_027', name:'Vừa đi bộ vừa nghe điện thoại trao đổi công việc', met:2.5, icon:'·'},
  {id:'act_028', name:'Ủi (là) quần áo phẳng', met:1.8, icon:'·'},
  {id:'act_029', name:'Phơi quần áo, treo đồ lên móc', met:2, icon:'⭐'},
  {id:'act_030', name:'Gấp quần áo, xếp vào tủ', met:2, icon:'⭐'},
  {id:'act_031', name:'Đổ rác, mang túi rác ra xe gom', met:2, icon:'⭐'},
  {id:'act_032', name:'Phủi bụi bàn ghế, kệ sách, tivi', met:2, icon:'⭐'},
  {id:'act_033', name:'Lau dọn bếp từ, bàn ăn sau khi ăn', met:2.3, icon:'⭐'},
  {id:'act_034', name:'Hút bụi toàn bộ căn nhà bằng máy', met:2.5, icon:'⭐'},
  {id:'act_035', name:'Rửa chén bát, dọn dẹp bồn rửa bếp', met:2.5, icon:'⭐'},
  {id:'act_036', name:'Nấu ăn, sơ chế cắt thái thực phẩm', met:2.5, icon:'⭐'},
  {id:'act_037', name:'Tưới cây, tỉa cành ban công, sân vườn', met:2.5, icon:'·'},
  {id:'act_038', name:'Quét nhà, dọn rác sàn', met:3, icon:'⭐'},
  {id:'act_039', name:'Rửa xe máy tại nhà', met:3, icon:'⭐'},
  {id:'act_040', name:'Lau cửa kính, cửa sổ ban công', met:3.2, icon:'·'},
  {id:'act_041', name:'Lau nhà bằng cây lau thông thường', met:3.5, icon:'⭐'},
  {id:'act_042', name:'Cọ rửa nhà vệ sinh, sàn phòng tắm', met:3.5, icon:'⭐'},
  {id:'act_043', name:'Sắp xếp lại đồ đạc, decor nhẹ phòng', met:3.5, icon:'·'},
  {id:'act_044', name:'Rửa xe ô tô tại nhà', met:3.5, icon:'·'},
  {id:'act_045', name:'Giặt quần áo bằng tay (chà, vắt)', met:4, icon:'·'},
  {id:'act_046', name:'Làm vườn chuyên sâu, cuốc đất, nhổ cỏ', met:4.5, icon:'·'},
  {id:'act_047', name:'Di chuyển nội thất nặng, bê vác tủ giường', met:7, icon:'·'},
  {id:'act_048', name:'Cho em bé ăn, đút bột (ngồi)', met:1.5, icon:'⭐'},
  {id:'act_049', name:'Đọc truyện tranh, sách cho con nghe', met:1.5, icon:'·'},
  {id:'act_050', name:'Tắm rửa và lau người cho em bé', met:2, icon:'⭐'},
  {id:'act_051', name:'Chơi đùa với trẻ em (ngồi xếp hình, vẽ tranh)', met:2, icon:'⭐'},
  {id:'act_052', name:'Thu gom đồ chơi của con sau khi chơi', met:2.2, icon:'⭐'},
  {id:'act_053', name:'Bế em bé, đi lại vỗ về nhẹ nhàng', met:2.5, icon:'⭐'},
  {id:'act_054', name:'Dắt xe đẩy nôi em bé đi dạo', met:2.5, icon:'⭐'},
  {id:'act_055', name:'Đi bộ dắt tay trẻ em đi dạo công viên', met:3, icon:'⭐'},
  {id:'act_056', name:'Đeo đai địu con đi lại, di chuyển', met:3.2, icon:'·'},
  {id:'act_057', name:'Chơi đùa với trẻ em tích cực (chạy nhảy, trốn tìm)', met:5, icon:'⭐'},
  {id:'act_058', name:'Đứng xếp hàng thanh toán tại quầy thu ngân', met:1.3, icon:'⭐'},
  {id:'act_059', name:'Thử đồ, thay đổi trang phục khi mua sắm', met:2, icon:'·'},
  {id:'act_060', name:'Đi siêu thị đẩy xe hàng tốc độ chậm', met:2.3, icon:'⭐'},
  {id:'act_061', name:'Đi mua sắm quần áo tại TTTM (đi bộ nhiều)', met:2.5, icon:'⭐'},
  {id:'act_062', name:'Đi chợ truyền thống, xách giỏ đồ nhẹ', met:3, icon:'⭐'},
  {id:'act_063', name:'Bốc xếp hàng hóa mua sắm lên cốp xe ô tô', met:3, icon:'·'},
  {id:'act_064', name:'Đẩy xe hàng nặng trong siêu thị lớn', met:3.5, icon:'·'},
  {id:'act_065', name:'Xách túi đồ mua sắm nặng (>5kg) đi bộ', met:4, icon:'·'},
  {id:'act_066', name:'Ngồi trên xe bus, xe khách, máy bay di chuyển', met:1.3, icon:'⭐'},
  {id:'act_067', name:'Đứng bám tay vịn trên xe bus, tàu điện ngầm', met:1.8, icon:'·'},
  {id:'act_068', name:'Lái xe máy di chuyển trong thành phố', met:2, icon:'⭐'},
  {id:'act_069', name:'Lái xe ô tô con cá nhân', met:2.5, icon:'⭐'},
  {id:'act_070', name:'Đi bộ tốc độ chậm thả lỏng (< 3 km/h)', met:2.5, icon:'⭐'},
  {id:'act_071', name:'Đi bộ ra trạm xe bus, ga tàu điện', met:3, icon:'·'},
  {id:'act_072', name:'Đi bộ tốc độ trung bình (3 - 4.5 km/h)', met:3.3, icon:'⭐'},
  {id:'act_073', name:'Đi xuống cầu thang bộ', met:3.5, icon:'·'},
  {id:'act_074', name:'Đi bộ tốc độ nhanh, vội vã (4.8 - 5.5 km/h)', met:3.8, icon:'⭐'},
  {id:'act_075', name:'Đi bộ mang balo nặng (>5kg)', met:4.5, icon:'·'},
  {id:'act_076', name:'Leo cầu thang bộ liên tục', met:8, icon:'⭐'},
  {id:'act_077', name:'Khởi động nhẹ nhàng, xoay khớp, giãn cơ', met:2.5, icon:'⭐'},
  {id:'act_078', name:'Tập các bài cốt lõi Core, bụng (Plank, Crunch)', met:2.8, icon:'⭐'},
  {id:'act_079', name:'Tập với dây kháng lực cao su (Resistance bands)', met:3, icon:'·'},
  {id:'act_080', name:'Tập tạ cô lập cơ, tạ nhẹ (Isolation/Light weights)', met:3.5, icon:'⭐'},
  {id:'act_081', name:'Tập với máy kháng lực tập trung (Machine Press)', met:3.5, icon:'⭐'},
  {id:'act_082', name:'Bắn cung thể thao', met:3.5, icon:'·'},
  {id:'act_083', name:'Tập Calisthenics cơ bản (Pushup, Pullup, Dips vừa)', met:4.5, icon:'⭐'},
  {id:'act_084', name:'Chạy phục hồi nhẹ nhàng sau race - Pace 10:00', met:4.5, icon:'·'},
  {id:'act_085', name:'Tập Thể hình phân nhóm cơ (Bodybuilding vừa)', met:5, icon:'⭐'},
  {id:'act_086', name:'Tập Cardio trên máy Elliptical tốc độ vừa', met:5, icon:'⭐'},
  {id:'act_087', name:'Trượt ván đường phố (Skateboarding)', met:5, icon:'·'},
  {id:'act_088', name:'Đấm bao cát liên tục (Heavy bag training)', met:5.5, icon:'⭐'},
  {id:'act_089', name:'Chạy thả lỏng dưỡng sinh (Jogging) - Pace 8-9', met:6, icon:'⭐'},
  {id:'act_090', name:'Chạy bộ trên máy (Treadmill) - Tốc độ 6 km/h', met:6, icon:'⭐'},
  {id:'act_091', name:'Tập tạ nặng bài phức hợp (Squat/Deadlift/Bench)', met:6, icon:'⭐'},
  {id:'act_092', name:'Thể dục nhịp điệu (Aerobics) cường độ trung bình', met:6, icon:'⭐'},
  {id:'act_093', name:'Tập với máy chèo thuyền (Rowing machine) vừa', met:6, icon:'·'},
  {id:'act_094', name:'Chèo thuyền SUP tốc độ cao, tập cardio', met:6, icon:'·'},
  {id:'act_095', name:'Trượt patin, giày trượt có bánh (Rollerblading)', met:7, icon:'·'},
  {id:'act_096', name:'Tập Calisthenics nâng cao (Muscle up, Planche)', met:7.5, icon:'·'},
  {id:'act_097', name:'Chạy bộ trên máy (Treadmill) - Tốc độ 8 km/h', met:8, icon:'⭐'},
  {id:'act_098', name:'Tập HIIT, Circuit Training cường độ cao liên tục', met:8, icon:'⭐'},
  {id:'act_099', name:'Tập Kettlebell Swing (quai tạ ấm) liên tục', met:8, icon:'·'},
  {id:'act_100', name:'Leo núi nhân tạo trong nhà (Rock climbing)', met:8, icon:'·'},
  {id:'act_101', name:'Chạy bộ ngoài trời tốc độ chậm - Pace 7:00', met:8.3, icon:'⭐'},
  {id:'act_102', name:'Tập với máy chèo thuyền cường độ cao', met:8.5, icon:'·'},
  {id:'act_103', name:'Nhảy dây tốc độ chậm (<100 cái/phút)', met:8.8, icon:'⭐'},
  {id:'act_104', name:'Tập Cardio trên máy Stairmaster tốc độ vừa', met:9, icon:'⭐'},
  {id:'act_105', name:'Chạy bộ ngoài trời tốc độ trung bình - Pace 6:00', met:9.8, icon:'⭐'},
  {id:'act_106', name:'Chạy bộ trên máy (Treadmill) - Tốc độ 10 km/h', met:10, icon:'⭐'},
  {id:'act_107', name:'Chạy địa hình băng rừng lội suối (Trail running)', met:10, icon:'·'},
  {id:'act_108', name:'Tập Battle Ropes (quật dây thừng thể hình)', met:10, icon:'·'},
  {id:'act_109', name:'Tập Tabata chu kỳ cực ngắn cường độ cao', met:11, icon:'·'},
  {id:'act_110', name:'Tập Cardio trên máy Stairmaster tốc độ cao', met:11, icon:'·'},
  {id:'act_111', name:'Chạy biến tốc ngắn (Interval training)', met:11.5, icon:'·'},
  {id:'act_112', name:'Nhảy dây tốc độ trung bình (100-120 cái/phút)', met:11.8, icon:'⭐'},
  {id:'act_113', name:'Chạy bộ ngoài trời tốc độ nhanh - Pace 5:00', met:11.8, icon:'⭐'},
  {id:'act_114', name:'Tập Crossfit cường độ thi đấu', met:12, icon:'⭐'},
  {id:'act_115', name:'Nhảy dây tốc độ nhanh (>120 cái/phút)', met:12.3, icon:'·'},
  {id:'act_116', name:'Chạy bộ ngoài trời tốc độ rất nhanh - Pace 4:30', met:12.8, icon:'·'},
  {id:'act_117', name:'Chạy cự ly dài bán marathon/marathon', met:13.3, icon:'·'},
  {id:'act_118', name:'Chạy nước rút cự ly ngắn (Sprinting liên tục)', met:14.5, icon:'·'},
  {id:'act_119', name:'Chạy leo dốc liên tục, chạy leo đồi', met:15, icon:'·'},
  {id:'act_120', name:'Thiền định tĩnh tâm kết hợp kiểm soát hơi thở', met:1.3, icon:'·'},
  {id:'act_121', name:'Yin Yoga giữ tư thế lâu sâu', met:2, icon:'·'},
  {id:'act_122', name:'Hatha Yoga, Yoga phục hồi thư giãn chậm', met:2.5, icon:'⭐'},
  {id:'act_123', name:'Pilates trên thảm cơ bản (Mat Pilates)', met:3, icon:'⭐'},
  {id:'act_124', name:'Pilates sử dụng máy chuyên dụng (Reformer)', met:3.5, icon:'⭐'},
  {id:'act_125', name:'Yoga dây, Yoga bay (Aerial Yoga)', met:3.5, icon:'·'},
  {id:'act_126', name:'Vinyasa Yoga, Power Yoga chuỗi nhanh', met:4, icon:'⭐'},
  {id:'act_127', name:'Bikram Yoga (Tập Yoga trong phòng nóng)', met:4, icon:'·'},
  {id:'act_128', name:'Pilates tăng cường với tạ nhỏ và vòng', met:4, icon:'·'},
  {id:'act_129', name:'Ashtanga Yoga cường độ cao nâng cao', met:4.5, icon:'·'},
  {id:'act_130', name:'Đạp xe đôi thư giãn công viên', met:3, icon:'·'},
  {id:'act_131', name:'Đạp xe đạp thong thả dạo phố (<15 km/h)', met:3.5, icon:'⭐'},
  {id:'act_132', name:'Đạp xe đi làm, đi học mang balo vừa', met:4, icon:'⭐'},
  {id:'act_133', name:'Đạp xe trong nhà với máy cố định - Mức nhẹ', met:4.8, icon:'⭐'},
  {id:'act_134', name:'Đạp xe đạp tốc độ chậm dưỡng sinh (15-19 km/h)', met:5.8, icon:'⭐'},
  {id:'act_135', name:'Đạp xe BMX nhào lộn nghệ thuật', met:7.5, icon:'·'},
  {id:'act_136', name:'Đạp xe đạp tốc độ trung bình thể thao (19-22 km/h)', met:8, icon:'⭐'},
  {id:'act_137', name:'Đạp xe địa hình đồi núi (Mountain biking)', met:8.5, icon:'·'},
  {id:'act_138', name:'Đạp xe trong nhà lớp Spinning - Cường độ cao', met:8.5, icon:'⭐'},
  {id:'act_139', name:'Đạp xe đạp tốc độ nhanh tính giờ (22-25 km/h)', met:10, icon:'·'},
  {id:'act_140', name:'Đạp xe trong nhà máy cố định - Cường độ cực cao', met:10.5, icon:'·'},
  {id:'act_141', name:'Đạp xe đường trường tốc độ rất nhanh (>25 km/h)', met:12, icon:'·'},
  {id:'act_142', name:'Bơi chó dạo nước vui vẻ, thả nổi', met:2.5, icon:'·'},
  {id:'act_143', name:'Bơi tự do hoặc bơi ếch thả lỏng thư giãn', met:3.5, icon:'⭐'},
  {id:'act_144', name:'Bơi lội thể dục thẩm mỹ dưới nước (Water aerobics)', met:4, icon:'·'},
  {id:'act_145', name:'Bơi ngửa kỹ thuật vừa phải', met:4.8, icon:'·'},
  {id:'act_146', name:'Bơi lặn có ống thở bề mặt (Snorkeling)', met:5, icon:'·'},
  {id:'act_147', name:'Bơi ếch tốc độ trung bình liên tục', met:5.3, icon:'⭐'},
  {id:'act_148', name:'Bơi sải (Trườn sấp) tốc độ trung bình', met:5.8, icon:'⭐'},
  {id:'act_149', name:'Bơi ngửa tốc độ nhanh liên tục', met:7, icon:'·'},
  {id:'act_150', name:'Bơi lặn sâu bình dưỡng khí (Scuba diving)', met:7, icon:'·'},
  {id:'act_151', name:'Bơi sải (Trườn sấp) tốc độ nhanh liên tục', met:9.8, icon:'⭐'},
  {id:'act_152', name:'Bơi ếch tốc độ nhanh thi đấu', met:10.3, icon:'·'},
  {id:'act_153', name:'Bơi bướm kỹ thuật tiêu chuẩn cường độ cao', met:11, icon:'·'},
  {id:'act_154', name:'Tập Thái Cực Quyền (Tai Chi) điều hòa hơi thở', met:2.5, icon:'·'},
  {id:'act_155', name:'Tập các bài quyền đơn độc (Kata/Taolu/Kiếm thuật)', met:4, icon:'·'},
  {id:'act_156', name:'Tập Aikido kỹ thuật tự vệ hóa giải', met:4.5, icon:'·'},
  {id:'act_157', name:'Tập đối luyện kỹ thuật nhẹ nhàng với bạn tập', met:6, icon:'⭐'},
  {id:'act_158', name:'Tập Vovinam / Võ cổ truyền Việt Nam', met:6, icon:'⭐'},
  {id:'act_159', name:'Tập đấu kiếm thể thao chuyên nghiệp (Fencing)', met:6, icon:'·'},
  {id:'act_160', name:'Tập võ Taekwondo / Karate đòn chân đòn tay', met:7, icon:'⭐'},
  {id:'act_161', name:'Tập Judo / Brazilian Jiu-Jitsu (BJJ) vật khóa sàn', met:7, icon:'⭐'},
  {id:'act_162', name:'Thi đấu võ thuật đối kháng (Boxing/Kickboxing)', met:10, icon:'⭐'},
  {id:'act_163', name:'Tập Tán thủ (Sanda) / Muay Thai cường độ cao', met:10.5, icon:'·'},
  {id:'act_164', name:'Bóng bàn (Đánh đôi giải trí nhẹ nhàng)', met:3, icon:'·'},
  {id:'act_165', name:'Bóng đá (Vị trí thủ môn / Tập chuyền sút nhẹ)', met:4, icon:'⭐'},
  {id:'act_166', name:'Bóng chuyền (Trong nhà thi đấu phong trào)', met:4, icon:'⭐'},
  {id:'act_167', name:'Bóng bàn (Ping pong đánh đơn phong trào)', met:4, icon:'⭐'},
  {id:'act_168', name:'Bóng chày (Các vị trí bắt bóng, chạy)', met:4, icon:'·'},
  {id:'act_169', name:'Cầu lông / Pickleball (Đánh đôi giải trí nhẹ)', met:4.5, icon:'⭐'},
  {id:'act_170', name:'Bóng rổ (Tập ném rổ, chơi nửa sân phong trào)', met:4.5, icon:'⭐'},
  {id:'act_171', name:'Tennis (Quần vợt đánh đôi phối hợp)', met:5, icon:'⭐'},
  {id:'act_172', name:'Pickleball (Chơi đơn di chuyển bao sân tích cực)', met:6, icon:'⭐'},
  {id:'act_173', name:'Bóng chày (Vị trí ném bóng Pitcher)', met:6, icon:'·'},
  {id:'act_174', name:'Bóng đá (Trận đấu phong trào sân 5 hoặc sân 7)', met:7, icon:'⭐'},
  {id:'act_175', name:'Cầu lông (Đánh đơn phong trào tích cực)', met:7, icon:'⭐'},
  {id:'act_176', name:'Tennis (Quần vợt đánh đơn di chuyển rộng)', met:7.3, icon:'⭐'},
  {id:'act_177', name:'Bóng rổ (Trận đấu thi đấu chính thức)', met:8, icon:'⭐'},
  {id:'act_178', name:'Bóng chuyền bãi biển di chuyển trên cát', met:8, icon:'·'},
  {id:'act_179', name:'Bóng ném / Bóng bầu dục thi đấu', met:8, icon:'·'},
  {id:'act_180', name:'Futsal (Bóng đá trong nhà cường độ bùng nổ)', met:9, icon:'·'},
  {id:'act_181', name:'Nhân viên bảo vệ tòa nhà (Ngồi trực camera)', met:1.3, icon:'⭐'},
  {id:'act_182', name:'Thợ làm móng, nail (Ngồi thao tác tỉ mỉ)', met:1.5, icon:'⭐'},
  {id:'act_183', name:'Tài xế taxi, xe công nghệ, xe tải (Lái xe liên tục)', met:1.5, icon:'⭐'},
  {id:'act_184', name:'Công nhân dây chuyền (Ngồi lắp ráp cơ bản)', met:1.8, icon:'·'},
  {id:'act_185', name:'Bác sĩ phẫu thuật (Đứng tập trung cao độ)', met:2, icon:'·'},
  {id:'act_186', name:'Thợ cắt tóc, tạo mẫu tóc (Đứng thao tác liên tục)', met:2, icon:'⭐'},
  {id:'act_187', name:'Nhân viên bảo vệ (Đứng gác cổng, điều phối xe)', met:2, icon:'⭐'},
  {id:'act_188', name:'Shipper xe máy (Lên xuống xe, giao hàng nhẹ)', met:2.5, icon:'⭐'},
  {id:'act_189', name:'Công nhân dây chuyền sản xuất (Đứng thao tác)', met:2.5, icon:'⭐'},
  {id:'act_190', name:'Pha chế nước, Barista, Bartender (Đứng thao tác)', met:2.5, icon:'⭐'},
  {id:'act_191', name:'Điều dưỡng, Y tá (Di chuyển hỗ trợ bệnh nhân)', met:3, icon:'⭐'},
  {id:'act_192', name:'Thợ sửa chữa xe máy, ô tô (Cúi người vặn ốc)', met:3, icon:'⭐'},
  {id:'act_193', name:'Phục vụ nhà hàng, quán cafe (Đi lại liên tục)', met:3, icon:'⭐'},
  {id:'act_194', name:'Nhân viên bảo vệ (Đi tuần tra khuôn viên rộng)', met:3, icon:'⭐'},
  {id:'act_195', name:'Thợ điện dân dụng (Đi dây, đập đục tường)', met:3.3, icon:'·'},
  {id:'act_196', name:'Sales thị trường (Đi bộ liên tục gặp khách hàng)', met:3.5, icon:'⭐'},
  {id:'act_197', name:'Shipper giao hàng đi bộ (Chặng cuối ngõ, chung cư)', met:3.5, icon:'⭐'},
  {id:'act_198', name:'Kỹ thuật viên hiện trường (Bảo trì máy công nghiệp)', met:3.5, icon:'⭐'},
  {id:'act_199', name:'Đan/Móc/May vá thủ công', met:1.5, icon:'·'},
  {id:'act_200', name:'Chơi game PC / Console (Ngồi)', met:1.3, icon:'⭐'},
  {id:'act_201', name:'Đánh golf (Ngồi xe điện di chuyển)', met:2.5, icon:'·'},
  {id:'act_202', name:'Đánh golf (Tập tại thảm Driving Range)', met:3, icon:'·'},
  {id:'act_203', name:'Đánh golf (Đi bộ tự kéo túi gậy hoặc có caddie)', met:3.8, icon:'·'},
  {id:'act_204', name:'Dọn dẹp buồng phòng khách sạn', met:4, icon:'·'},
  {id:'act_205', name:'Thợ mộc, chế tác đồ gỗ (Cưa cắt, chà nhám)', met:4, icon:'·'},
  {id:'act_206', name:'Thợ sơn nước (Lăn sơn tường, leo giàn giáo)', met:4, icon:'·'},
  {id:'act_207', name:'Nông dân làm đồng (Thu hoạch hoa màu thủ công)', met:4, icon:'·'},
  {id:'act_208', name:'Shipper xe máy (Giao hàng cồng kềnh, bê nặng)', met:4.5, icon:'·'},
  {id:'act_209', name:'Thợ xây dựng, thợ nề (Trộn vữa, khuấy hồ, xây)', met:5, icon:'⭐'},
  {id:'act_210', name:'Trò chơi thực tế ảo (VR Game bùng nổ)', met:5, icon:'·'},
  {id:'act_211', name:'Nhảy hiện đại, Kpop dance, Shuffle', met:5, icon:'⭐'},
  {id:'act_212', name:'Kỹ thuật viên viễn thông (Leo cột, kéo cáp)', met:6, icon:'·'},
  {id:'act_213', name:'Công nhân bốc xếp kho bãi (Bê vác kiện nặng)', met:6.5, icon:'⭐'}
];

function searchAct(q) {
  if (!q) return ACT_DB;
  const k = _noTone(q.trim());
  return ACT_DB.filter(a => _noTone(a.name).includes(k));
}

function actKcal(met, weightKg, minutes) {
  return Math.round(met * weightKg * (minutes / 60));
}

if (typeof window !== 'undefined') { window.ACT_DB = ACT_DB; window.searchAct = searchAct; window.actKcal = actKcal; }
if (typeof module !== 'undefined' && module.exports) module.exports = { ACT_DB, searchAct, actKcal };
