const FOOD_DB = [
  {id:'pho_bo_tai', name:'Phở Bò tái', kcal:450, protein:28, carb:55, fat:12, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'pho_bo_nam_gau', name:'Phở Bò nạm/gầu', kcal:520, protein:30, carb:55, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'pho_bo_dac_biet', name:'Phở Bò đặc biệt', kcal:600, protein:35, carb:58, fat:22, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'pho_ga', name:'Phở Gà', kcal:400, protein:26, carb:55, fat:8, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_bo_hue_chuan', name:'Bún bò Huế Chuẩn', kcal:550, protein:30, carb:65, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_rieu_cua', name:'Bún riêu Cua', kcal:480, protein:22, carb:60, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_cha_ha_noi', name:'Bún chả Hà Nội', kcal:600, protein:32, carb:70, fat:20, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'bun_thit_nuong_chuan', name:'Bún thịt nướng Chuẩn', kcal:550, protein:28, carb:65, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'bun_mam_chuan', name:'Bún mắm Chuẩn', kcal:500, protein:25, carb:65, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_ca_chuan', name:'Bún cá Chuẩn', kcal:450, protein:28, carb:55, fat:12, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'hu_tieu_nam_vang', name:'Hủ tiếu Nam Vang', kcal:480, protein:25, carb:60, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'hu_tieu_my', name:'Hủ tiếu Mỳ', kcal:500, protein:26, carb:60, fat:16, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_quang_chuan', name:'Mì Quảng Chuẩn', kcal:550, protein:28, carb:62, fat:20, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'cao_lau_hoi_an', name:'Cao lầu Hội An', kcal:520, protein:25, carb:65, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'com_tam_suon', name:'Cơm tấm Sườn', kcal:700, protein:35, carb:80, fat:25, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_tam_suon_bi_cha', name:'Cơm tấm Sườn bì chả', kcal:850, protein:40, carb:85, fat:35, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_ga_hai_nam', name:'Cơm gà Hải Nam', kcal:650, protein:35, carb:75, fat:20, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_ga_xoi_mo', name:'Cơm gà Xối mỡ', kcal:750, protein:35, carb:80, fat:28, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_chien_duong_chau', name:'Cơm chiên Dương Châu', kcal:600, protein:20, carb:75, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_chien_hai_san', name:'Cơm chiên Hải sản', kcal:580, protein:25, carb:70, fat:20, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_trang', name:'Cơm trắng', kcal:200, protein:4, carb:45, fat:0.5, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'com_trang_2', name:'Cơm trắng', kcal:400, protein:8, carb:90, fat:1, fiber:0, sugar:0, serving:1, unit:'tô lớn', processed:0},
  {id:'chao_long_chuan', name:'Cháo lòng Chuẩn', kcal:400, protein:20, carb:45, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'chao_ga_chuan', name:'Cháo gà Chuẩn', kcal:350, protein:22, carb:45, fat:8, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'chao_trang', name:'Cháo trắng', kcal:150, protein:3, carb:32, fat:0.5, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'banh_mi_thit_nguoi', name:'Bánh mì Thịt nguội', kcal:450, protein:18, carb:50, fat:18, fiber:0, sugar:0, serving:1, unit:'ổ', processed:1},
  {id:'banh_mi_thit_nuong', name:'Bánh mì Thịt nướng', kcal:500, protein:22, carb:55, fat:20, fiber:0, sugar:0, serving:1, unit:'ổ', processed:1},
  {id:'banh_mi_cha_ca', name:'Bánh mì Chả cá', kcal:420, protein:20, carb:50, fat:15, fiber:0, sugar:0, serving:1, unit:'ổ', processed:0},
  {id:'banh_mi_xiu_mai', name:'Bánh mì Xíu mại', kcal:480, protein:20, carb:52, fat:20, fiber:0, sugar:0, serving:1, unit:'ổ', processed:1},
  {id:'banh_mi_trung', name:'Bánh mì Trứng', kcal:400, protein:15, carb:45, fat:18, fiber:0, sugar:0, serving:1, unit:'ổ', processed:0},
  {id:'banh_xeo_tom_thit', name:'Bánh xèo Tôm thịt', kcal:450, protein:20, carb:45, fat:22, fiber:0, sugar:0, serving:1, unit:'cái lớn', processed:1},
  {id:'banh_khot_chuan', name:'Bánh khọt Chuẩn', kcal:400, protein:18, carb:42, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'banh_cuon_thit', name:'Bánh cuốn Thịt', kcal:350, protein:15, carb:50, fat:10, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'banh_canh_cua', name:'Bánh canh Cua', kcal:480, protein:25, carb:60, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'banh_canh_gio_heo', name:'Bánh canh Giò heo', kcal:550, protein:28, carb:60, fat:22, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'lau_thai_1_nguoi', name:'Lẩu Thái 1 người', kcal:600, protein:35, carb:60, fat:20, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'lau_mam_1_nguoi', name:'Lẩu mắm 1 người', kcal:550, protein:30, carb:55, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'lau_ga_la_e_1_nguoi', name:'Lẩu gà lá é 1 người', kcal:500, protein:32, carb:45, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'goi_cuon_tom_thit', name:'Gỏi cuốn Tôm thịt', kcal:110, protein:5, carb:18, fat:2, fiber:0, sugar:0, serving:1, unit:'cuốn', processed:0},
  {id:'cha_gio_chien', name:'Chả giò Chiên', kcal:150, protein:5, carb:12, fat:8, fiber:0, sugar:0, serving:1, unit:'cuốn', processed:1},
  {id:'nem_nuong_nha_trang', name:'Nem nướng Nha Trang', kcal:450, protein:22, carb:45, fat:20, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'thit_kho_tau_trung', name:'Thịt kho Tàu (trứng)', kcal:350, protein:22, carb:8, fat:25, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'ca_kho_to', name:'Cá kho Tộ', kcal:280, protein:25, carb:5, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'ga_kho_gung', name:'Gà kho Gừng', kcal:320, protein:28, carb:8, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'thit_luoc_heo', name:'Thịt luộc Heo', kcal:250, protein:20, carb:0, fat:18, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'rau_xao_toi', name:'Rau xào Tỏi', kcal:120, protein:3, carb:10, fat:8, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'rau_muong_xao_toi', name:'Rau muống Xào tỏi', kcal:110, protein:3, carb:10, fat:7, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'canh_chua_ca', name:'Canh chua Cá', kcal:100, protein:12, carb:8, fat:3, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'canh_rau_thit_bam', name:'Canh rau Thịt bằm', kcal:80, protein:8, carb:6, fat:3, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'trung_chien_op_la', name:'Trứng chiên Ốp la', kcal:90, protein:6, carb:0.5, fat:7, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'bun_dau_mam_tom', name:'Bún đậu Mắm tôm', kcal:850, protein:32, carb:75, fat:40, fiber:0, sugar:0, serving:1, unit:'mẹt', processed:1},
  {id:'bun_oc_chuan', name:'Bún ốc Chuẩn', kcal:400, protein:18, carb:55, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_moc_chuan', name:'Bún mọc Chuẩn', kcal:450, protein:22, carb:58, fat:12, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mien_ga_chuan', name:'Miến gà Chuẩn', kcal:380, protein:25, carb:50, fat:8, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mien_luon_chuan', name:'Miến lươn Chuẩn', kcal:420, protein:25, carb:55, fat:12, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'pho_cuon_ha_noi', name:'Phở cuốn Hà Nội', kcal:90, protein:6, carb:10, fat:3, fiber:0, sugar:0, serving:1, unit:'cuốn', processed:0},
  {id:'pho_xao_bo', name:'Phở xào Bò', kcal:620, protein:28, carb:70, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'mi_xao_gion_hai_san', name:'Mì xào Giòn hải sản', kcal:680, protein:25, carb:75, fat:28, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'mi_xao_mem_bo', name:'Mì xào Mềm bò', kcal:620, protein:28, carb:70, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'hoanh_thanh_mi', name:'Hoành thánh Mì', kcal:450, protein:22, carb:55, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'banh_bao_thit_trung', name:'Bánh bao Thịt trứng', kcal:280, protein:12, carb:35, fat:10, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_bao_chay', name:'Bánh bao Chay', kcal:200, protein:6, carb:32, fat:5, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_gio_chuan', name:'Bánh giò Chuẩn', kcal:320, protein:12, carb:40, fat:12, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'xoi_man_day_du', name:'Xôi mặn Đầy đủ', kcal:620, protein:18, carb:85, fat:20, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'xoi_ga_chuan', name:'Xôi gà Chuẩn', kcal:550, protein:25, carb:80, fat:15, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'xoi_xeo_chuan', name:'Xôi xéo Chuẩn', kcal:500, protein:12, carb:78, fat:14, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'xoi_che_ngot', name:'Xôi chè Ngọt', kcal:420, protein:8, carb:80, fat:5, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'com_cuon_han_viet_hoa', name:'Cơm cuộn Hàn (Việt hóa)', kcal:350, protein:12, carb:55, fat:8, fiber:0, sugar:0, serving:1, unit:'cuộn', processed:0},
  {id:'bot_chien_trung', name:'Bột chiên Trứng', kcal:500, protein:15, carb:55, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'banh_trang_tron', name:'Bánh tráng Trộn', kcal:350, protein:10, carb:50, fat:12, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_trang_nuong', name:'Bánh tráng Nướng', kcal:220, protein:8, carb:28, fat:8, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'banh_trang_cuon', name:'Bánh tráng Cuốn', kcal:120, protein:5, carb:18, fat:4, fiber:0, sugar:0, serving:1, unit:'cuốn', processed:0},
  {id:'ha_cao_hap', name:'Há cảo Hấp', kcal:50, protein:3, carb:6, fat:1.5, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_bot_loc_tom_thit', name:'Bánh bột lọc Tôm thịt', kcal:60, protein:3, carb:9, fat:1.5, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_nam_chuan', name:'Bánh nậm Chuẩn', kcal:70, protein:3, carb:11, fat:2, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_it_tran', name:'Bánh ít Trần', kcal:120, protein:4, carb:20, fat:3, fiber:0, sugar:0, serving:1, unit:'cái', processed:0},
  {id:'banh_duc_nong', name:'Bánh đúc Nóng', kcal:250, protein:10, carb:35, fat:8, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'banh_beo_hue_8_cai', name:'Bánh bèo Huế (8 cái)', kcal:280, protein:10, carb:40, fat:8, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'che_dau_den_nuoc_cot', name:'Chè đậu đen Nước cốt', kcal:250, protein:6, carb:45, fat:5, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_ba_mau_chuan', name:'Chè ba màu Chuẩn', kcal:300, protein:5, carb:50, fat:8, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_khuc_bach_chuan', name:'Chè khúc bạch Chuẩn', kcal:280, protein:8, carb:35, fat:12, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_thai_chuan', name:'Chè Thái Chuẩn', kcal:350, protein:6, carb:55, fat:10, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_troi_nuoc', name:'Chè trôi nước', kcal:250, protein:4, carb:45, fat:6, fiber:0, sugar:0, serving:1, unit:'chén', processed:1},
  {id:'tau_hu_nuoc_duong', name:'Tàu hủ Nước đường', kcal:150, protein:8, carb:22, fat:3, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'sua_chua_nep_cam', name:'Sữa chua Nếp cẩm', kcal:220, protein:8, carb:35, fat:5, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'kem_trang_tien', name:'Kem Tràng Tiền', kcal:180, protein:3, carb:25, fat:8, fiber:0, sugar:0, serving:1, unit:'cây', processed:1},
  {id:'tra_sua_tran_chau_size_m', name:'Trà sữa Trân châu (size M)', kcal:350, protein:5, carb:60, fat:10, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'tra_sua_tran_chau_size_l', name:'Trà sữa Trân châu (size L)', kcal:500, protein:7, carb:85, fat:14, fiber:0, sugar:0, serving:1, unit:'700ml', processed:1},
  {id:'tra_dao_cam_sa', name:'Trà đào Cam sả', kcal:180, protein:1, carb:45, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'ca_phe_sua_da_chuan', name:'Cà phê sữa đá Chuẩn', kcal:150, protein:3, carb:25, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'ca_phe_den_da', name:'Cà phê đen Đá', kcal:5, protein:0, carb:1, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'bac_xiu_chuan', name:'Bạc xỉu Chuẩn', kcal:200, protein:4, carb:30, fat:6, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'nuoc_mia_chuan', name:'Nước mía Chuẩn', kcal:180, protein:0, carb:45, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'sinh_to_bo_chuan', name:'Sinh tố bơ Chuẩn', kcal:350, protein:6, carb:40, fat:18, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'sinh_to_xoai_chuan', name:'Sinh tố xoài Chuẩn', kcal:250, protein:4, carb:50, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'nuoc_cam_vat', name:'Nước cam Vắt', kcal:120, protein:2, carb:28, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nem_chua_ran', name:'Nem chua Rán', kcal:90, protein:5, carb:5, fat:6, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'cha_ca_la_vong', name:'Chả cá Lã Vọng', kcal:450, protein:30, carb:30, fat:22, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'cha_lua', name:'Chả lụa', kcal:200, protein:12, carb:5, fat:14, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'tom_nuong_muoi_ot', name:'Tôm nướng Muối ớt', kcal:120, protein:22, carb:1, fat:3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'muc_nuong_muoi_ot', name:'Mực nướng Muối ớt', kcal:140, protein:18, carb:4, fat:5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_nuong_trui_la_chuoi', name:'Cá nướng Trui/lá chuối', kcal:180, protein:22, carb:1, fat:10, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ga_nuong_muoi_ot_dui', name:'Gà nướng Muối ớt (đùi)', kcal:280, protein:28, carb:0, fat:18, fiber:0, sugar:0, serving:1, unit:'đùi', processed:0},
  {id:'ga_nuong_mat_ong', name:'Gà nướng Mật ong', kcal:320, protein:28, carb:8, fat:18, fiber:0, sugar:0, serving:1, unit:'đùi', processed:1},
  {id:'canh_ga_chien_nuoc_mam', name:'Cánh gà Chiên nước mắm', kcal:320, protein:22, carb:8, fat:22, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'heo_quay', name:'Heo quay', kcal:350, protein:22, carb:0, fat:28, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'vit_quay', name:'Vịt quay', kcal:320, protein:19, carb:0, fat:28, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'bo_ne_banh_mi', name:'Bò né Bánh mì', kcal:650, protein:35, carb:50, fat:35, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'bo_bit_tet_chuan', name:'Bò bít tết Chuẩn', kcal:550, protein:40, carb:25, fat:30, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'long_lon_luoc_nuong', name:'Lòng lợn Luộc/nướng', kcal:230, protein:14, carb:2, fat:18, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'tiet_canh', name:'Tiết canh', kcal:150, protein:18, carb:2, fat:6, fiber:0, sugar:0, serving:1, unit:'chén', processed:1},
  {id:'oc_luoc_xao', name:'Ốc Luộc/xào', kcal:250, protein:25, carb:25, fat:5, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'khoai_lang_nuong', name:'Khoai lang Nướng', kcal:130, protein:2, carb:30, fat:0, fiber:0, sugar:0, serving:1, unit:'củ vừa', processed:0},
  {id:'khoai_mi_hap_nuong', name:'Khoai mì Hấp/nướng', kcal:160, protein:1, carb:38, fat:0, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bap_luoc', name:'Bắp Luộc', kcal:100, protein:3, carb:22, fat:1, fiber:0, sugar:0, serving:1, unit:'trái', processed:0},
  {id:'bap_xao_bo', name:'Bắp Xào bơ', kcal:250, protein:5, carb:35, fat:12, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'dau_hu_chien', name:'Đậu hũ Chiên', kcal:200, protein:12, carb:8, fat:14, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_hu_sot_ca', name:'Đậu hũ Sốt cà', kcal:180, protein:11, carb:12, fat:10, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trung_vit_lon', name:'Trứng vịt lộn', kcal:180, protein:14, carb:2, fat:12, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trung_cut_lon_luoc_5_qua', name:'Trứng cút Lộn/luộc (5 quả)', kcal:100, protein:9, carb:1, fat:7, fiber:0, sugar:0, serving:5, unit:'quả', processed:0},
  {id:'banh_chuoi_nuong_chien', name:'Bánh chuối Nướng/chiên', kcal:250, protein:4, carb:38, fat:10, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'che_dau_den_nuoc_cot_dua', name:'Chè đậu đen Nước cốt dừa', kcal:250, protein:6, carb:45, fat:5, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_dau_xanh_danh_nuoc', name:'Chè đậu xanh Đánh/nước', kcal:220, protein:7, carb:42, fat:3, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'che_thai_chuan_2', name:'Chè thái Chuẩn', kcal:350, protein:6, carb:55, fat:10, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_buoi_chuan', name:'Chè bưởi Chuẩn', kcal:280, protein:4, carb:52, fat:6, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_troi_nuoc_chuan', name:'Chè trôi nước Chuẩn', kcal:250, protein:4, carb:45, fat:6, fiber:0, sugar:0, serving:1, unit:'chén', processed:1},
  {id:'che_hat_sen_long_nhan', name:'Chè hạt sen Long nhãn', kcal:180, protein:5, carb:35, fat:2, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'che_dau_do_chuan', name:'Chè đậu đỏ Chuẩn', kcal:240, protein:7, carb:48, fat:2, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'che_khoai_mon_nuoc_cot', name:'Chè khoai môn Nước cốt', kcal:260, protein:4, carb:48, fat:6, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'che_chuoi_nuoc_cot_dua', name:'Chè chuối Nước cốt dừa', kcal:280, protein:3, carb:45, fat:10, fiber:0, sugar:0, serving:1, unit:'chén', processed:1},
  {id:'che_suong_sa_hat_luu_chuan', name:'Chè sương sa hạt lựu Chuẩn', kcal:220, protein:2, carb:45, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'yaourt_da', name:'Yaourt Đá', kcal:180, protein:6, carb:30, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'rau_cau_dua_la_dua', name:'Rau câu Dừa/lá dứa', kcal:90, protein:1, carb:18, fat:2, fiber:0, sugar:0, serving:1, unit:'miếng', processed:0},
  {id:'banh_flan_caramel', name:'Bánh flan Caramel', kcal:120, protein:4, carb:15, fat:5, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'kem_que_socola', name:'Kem Que/socola', kcal:220, protein:3, carb:28, fat:12, fiber:0, sugar:0, serving:1, unit:'cây', processed:1},
  {id:'kem_ly', name:'Kem Ly', kcal:250, protein:5, carb:30, fat:14, fiber:0, sugar:0, serving:1, unit:'ly nhỏ', processed:1},
  {id:'banh_su_kem_vanilla', name:'Bánh su kem Vanilla', kcal:120, protein:2, carb:14, fat:7, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'banh_tiramisu_chuan', name:'Bánh tiramisu Chuẩn', kcal:320, protein:5, carb:30, fat:20, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'banh_mousse_chocolate', name:'Bánh mousse Chocolate', kcal:350, protein:5, carb:35, fat:22, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'banh_cheesecake_new_york', name:'Bánh cheesecake New York', kcal:380, protein:7, carb:30, fat:26, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'panna_cotta_dau_xoai', name:'Panna cotta Dâu/xoài', kcal:220, protein:4, carb:24, fat:12, fiber:0, sugar:0, serving:1, unit:'hũ', processed:1},
  {id:'trai_cay_dua_hau', name:'Trái cây Dưa hấu', kcal:30, protein:0.6, carb:8, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_xoai_chin', name:'Trái cây Xoài chín', kcal:65, protein:0.8, carb:17, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_xoai_xanh', name:'Trái cây Xoài xanh', kcal:50, protein:0.5, carb:13, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_chuoi', name:'Trái cây Chuối', kcal:105, protein:1.3, carb:27, fat:0.4, fiber:0, sugar:0, serving:1, unit:'quả vừa', processed:0},
  {id:'trai_cay_tao', name:'Trái cây Táo', kcal:95, protein:0.5, carb:25, fat:0.3, fiber:0, sugar:0, serving:1, unit:'quả vừa', processed:0},
  {id:'trai_cay_cam', name:'Trái cây Cam', kcal:65, protein:1.2, carb:16, fat:0.2, fiber:0, sugar:0, serving:1, unit:'quả vừa', processed:0},
  {id:'trai_cay_quyt', name:'Trái cây Quýt', kcal:45, protein:0.7, carb:12, fat:0.2, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trai_cay_oi', name:'Trái cây Ổi', kcal:68, protein:2.6, carb:14, fat:1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_thanh_long', name:'Trái cây Thanh long', kcal:50, protein:1.1, carb:12, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_nho', name:'Trái cây Nho', kcal:70, protein:0.7, carb:18, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_dua_thom', name:'Trái cây Dứa (thơm)', kcal:50, protein:0.5, carb:13, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_buoi', name:'Trái cây Bưởi', kcal:42, protein:0.8, carb:11, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_mit', name:'Trái cây Mít', kcal:95, protein:1.7, carb:24, fat:0.6, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_sau_rieng', name:'Trái cây Sầu riêng', kcal:150, protein:2, carb:27, fat:5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_bo', name:'Trái cây Bơ', kcal:160, protein:2, carb:9, fat:15, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_vai', name:'Trái cây Vải', kcal:66, protein:0.8, carb:17, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_nhan', name:'Trái cây Nhãn', kcal:60, protein:1, carb:15, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_mang_cut', name:'Trái cây Măng cụt', kcal:73, protein:0.5, carb:18, fat:0.6, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_chom_chom', name:'Trái cây Chôm chôm', kcal:68, protein:0.9, carb:17, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trai_cay_dau_tay', name:'Trái cây Dâu tây', kcal:32, protein:0.7, carb:8, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nuoc_uong_nuoc_loc', name:'Nước uống Nước lọc', kcal:0, protein:0, carb:0, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:0},
  {id:'nuoc_uong_nuoc_dua', name:'Nước uống Nước dừa', kcal:60, protein:1, carb:15, fat:0, fiber:0, sugar:0, serving:1, unit:'trái', processed:0},
  {id:'nuoc_uong_nuoc_cam_vat', name:'Nước uống Nước cam vắt', kcal:120, protein:2, carb:28, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nuoc_uong_nuoc_ep_thom', name:'Nước uống Nước ép thơm', kcal:110, protein:1, carb:26, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nuoc_uong_sinh_to_bo', name:'Nước uống Sinh tố bơ', kcal:350, protein:6, carb:40, fat:18, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nuoc_uong_sinh_to_xoai', name:'Nước uống Sinh tố xoài', kcal:250, protein:4, carb:50, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'nuoc_uong_sinh_to_chuoi', name:'Nước uống Sinh tố chuối', kcal:220, protein:5, carb:45, fat:3, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nuoc_uong_nuoc_mia', name:'Nước uống Nước mía', kcal:180, protein:0, carb:45, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'nuoc_uong_tra_dao_cam_sa', name:'Nước uống Trà đào cam sả', kcal:180, protein:1, carb:45, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'nuoc_uong_tra_tac', name:'Nước uống Trà tắc', kcal:140, protein:0, carb:35, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'nuoc_uong_tra_chanh', name:'Nước uống Trà chanh', kcal:120, protein:0, carb:30, fat:0, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'nuoc_uong_tra_sua_tran_chau', name:'Nước uống Trà sữa trân châu', kcal:350, protein:5, carb:60, fat:10, fiber:0, sugar:0, serving:1, unit:'Size M', processed:1},
  {id:'nuoc_uong_tra_sua_tran_chau_2', name:'Nước uống Trà sữa trân châu', kcal:500, protein:7, carb:85, fat:14, fiber:0, sugar:0, serving:1, unit:'Size L', processed:1},
  {id:'nuoc_uong_ca_phe_den_da', name:'Nước uống Cà phê đen đá', kcal:5, protein:0, carb:1, fat:0, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'nuoc_uong_ca_phe_sua_da', name:'Nước uống Cà phê sữa đá', kcal:150, protein:3, carb:25, fat:4, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'nuoc_uong_bac_xiu', name:'Nước uống Bạc xỉu', kcal:200, protein:4, carb:30, fat:6, fiber:0, sugar:0, serving:1, unit:'ly', processed:1},
  {id:'nuoc_uong_sua_dau_nanh', name:'Nước uống Sữa đậu nành', kcal:140, protein:7, carb:18, fat:4, fiber:0, sugar:0, serving:1, unit:'300ml', processed:0},
  {id:'nuoc_uong_sua_tuoi_khong_duo', name:'Nước uống Sữa tươi không đường', kcal:110, protein:8, carb:6, fat:6, fiber:0, sugar:0, serving:1, unit:'250ml', processed:0},
  {id:'nuoc_uong_coca_cola', name:'Nước uống Coca-Cola', kcal:139, protein:0, carb:35, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'nuoc_uong_pepsi', name:'Nước uống Pepsi', kcal:150, protein:0, carb:38, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'nuoc_uong_sting_dau', name:'Nước uống Sting dâu', kcal:160, protein:0, carb:40, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'nuoc_uong_red_bull', name:'Nước uống Red Bull', kcal:110, protein:1, carb:27, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 250ml', processed:1},
  {id:'nuoc_uong_monster_energy', name:'Nước uống Monster Energy', kcal:155, protein:0, carb:39, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'sushi_ca_hoi_1_mieng', name:'Sushi Cá hồi (1 miếng)', kcal:50, protein:4, carb:7, fat:1, fiber:0, sugar:0, serving:1, unit:'miếng', processed:0},
  {id:'sushi_set_10_mieng', name:'Sushi Set 10 miếng', kcal:500, protein:35, carb:70, fat:10, fiber:0, sugar:0, serving:10, unit:'miếng', processed:0},
  {id:'sashimi_ca_hoi', name:'Sashimi Cá hồi', kcal:200, protein:22, carb:0, fat:12, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ramen_tonkotsu', name:'Ramen Tonkotsu', kcal:700, protein:30, carb:75, fat:30, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'ramen_shoyu', name:'Ramen Shoyu', kcal:550, protein:28, carb:70, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'udon_bo', name:'Udon Bò', kcal:500, protein:22, carb:75, fat:12, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'com_bento_ga_teriyaki', name:'Cơm bento Gà teriyaki', kcal:650, protein:32, carb:85, fat:18, fiber:0, sugar:0, serving:1, unit:'hộp', processed:1},
  {id:'com_ca_ri_nhat_chuan', name:'Cơm cà ri Nhật Chuẩn', kcal:700, protein:25, carb:95, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'takoyaki_6_vien', name:'Takoyaki 6 viên', kcal:350, protein:12, carb:35, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'tonkatsu_heo', name:'Tonkatsu Heo', kcal:750, protein:35, carb:60, fat:40, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'kimbap_han', name:'Kimbap Hàn', kcal:300, protein:10, carb:50, fat:8, fiber:0, sugar:0, serving:1, unit:'cuộn', processed:0},
  {id:'bibimbap_bo', name:'Bibimbap Bò', kcal:600, protein:25, carb:80, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_cay_han_cap_3', name:'Mì cay Hàn (cấp 3)', kcal:650, protein:28, carb:75, fat:25, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'tokbokki_chuan', name:'Tokbokki Chuẩn', kcal:450, protein:8, carb:80, fat:10, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'ga_ran_han_sot_cay', name:'Gà rán Hàn Sốt cay', kcal:600, protein:30, carb:50, fat:30, fiber:0, sugar:0, serving:5, unit:'miếng', processed:1},
  {id:'bbq_han_bo_ba_chi_200g', name:'BBQ Hàn Bò ba chỉ (200g)', kcal:720, protein:35, carb:5, fat:55, fiber:0, sugar:0, serving:1, unit:'200g', processed:1},
  {id:'pad_thai_tom', name:'Pad Thái Tôm', kcal:550, protein:22, carb:65, fat:20, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'tom_yum_tom', name:'Tom Yum Tôm', kcal:250, protein:22, carb:18, fat:8, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'com_xanh_thai_ga', name:'Cơm xanh Thái Gà', kcal:650, protein:28, carb:80, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'pizza_pho_mai_slice', name:'Pizza Phô mai (slice)', kcal:280, protein:12, carb:35, fat:10, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'pizza_hai_san_slice', name:'Pizza Hải sản (slice)', kcal:300, protein:14, carb:35, fat:12, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'pizza_pepperoni_slice', name:'Pizza Pepperoni (slice)', kcal:320, protein:13, carb:36, fat:14, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'pizza_hawaiian_slice', name:'Pizza Hawaiian (slice)', kcal:290, protein:12, carb:35, fat:10, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'pasta_bolognese', name:'Pasta Bolognese', kcal:650, protein:25, carb:75, fat:25, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'pasta_carbonara', name:'Pasta Carbonara', kcal:750, protein:28, carb:75, fat:35, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'pasta_aglio_e_olio', name:'Pasta Aglio e Olio', kcal:520, protein:12, carb:70, fat:20, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'pasta_hai_san', name:'Pasta Hải sản', kcal:580, protein:28, carb:72, fat:18, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'burger_bo_pho_mai', name:'Burger Bò phô mai', kcal:550, protein:28, carb:45, fat:28, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'burger_ga', name:'Burger Gà', kcal:480, protein:25, carb:50, fat:20, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'burger_double_beef', name:'Burger Double beef', kcal:750, protein:40, carb:50, fat:42, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'hot_dog_chuan', name:'Hot dog Chuẩn', kcal:350, protein:12, carb:25, fat:22, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'khoai_tay_chien_size_m', name:'Khoai tây chiên Size M', kcal:350, protein:4, carb:45, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'ga_ran_kfc_1_mieng', name:'Gà rán KFC (1 miếng)', kcal:320, protein:20, carb:12, fat:20, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'ga_ran_mcdonald_s_1_mieng', name:'Gà rán McDonald’s (1 miếng)', kcal:300, protein:19, carb:12, fat:18, fiber:0, sugar:0, serving:1, unit:'miếng', processed:1},
  {id:'salad_caesar', name:'Salad Caesar', kcal:350, protein:12, carb:15, fat:25, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'salad_ca_ngu', name:'Salad Cá ngừ', kcal:280, protein:22, carb:18, fat:12, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'salad_uc_ga', name:'Salad Ức gà', kcal:320, protein:28, carb:18, fat:14, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'banh_croissant_bo', name:'Bánh croissant Bơ', kcal:280, protein:6, carb:30, fat:16, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'donut_glazed', name:'Donut Glazed', kcal:260, protein:3, carb:30, fat:14, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'taco_bo', name:'Taco Bò', kcal:380, protein:20, carb:35, fat:18, fiber:0, sugar:0, serving:2, unit:'cái', processed:0},
  {id:'burrito_bo', name:'Burrito Bò', kcal:650, protein:30, carb:75, fat:22, fiber:0, sugar:0, serving:1, unit:'cuộn', processed:1},
  {id:'nachos_pho_mai', name:'Nachos Phô mai', kcal:450, protein:10, carb:45, fat:25, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'fish_chips_kieu_anh', name:'Fish & Chips Kiểu Anh', kcal:700, protein:30, carb:60, fat:35, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'paella_hai_san', name:'Paella Hải sản', kcal:600, protein:28, carb:75, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'dimsum_ha_cao_xiu_mai_6_vien', name:'Dimsum Há cảo + xíu mại (6 viên)', kcal:320, protein:16, carb:42, fat:10, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'xiao_long_bao_tieu_long_bao', name:'Xiao Long Bao Tiểu long bao', kcal:360, protein:18, carb:45, fat:12, fiber:0, sugar:0, serving:6, unit:'viên', processed:0},
  {id:'com_tron_ga_han', name:'Cơm trộn Gà Hàn', kcal:550, protein:28, carb:75, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_y_sot_kem_nam', name:'Mì Ý Sốt kem nấm', kcal:680, protein:20, carb:78, fat:30, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'ga_popcorn_han_dai', name:'Gà popcorn Hàn/Đài', kcal:420, protein:22, carb:30, fat:22, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'tra_sua_matcha_nhat', name:'Trà sữa Matcha Nhật', kcal:320, protein:6, carb:55, fat:9, fiber:0, sugar:0, serving:1, unit:'500ml', processed:1},
  {id:'mochi_kem', name:'Mochi Kem', kcal:120, protein:2, carb:20, fat:4, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'bingsu_dau_xoai', name:'Bingsu Dâu/xoài', kcal:350, protein:6, carb:65, fat:8, fiber:0, sugar:0, serving:1, unit:'tô nhỏ', processed:1},
  {id:'yogurt_greek_granola', name:'Yogurt Greek Granola', kcal:250, protein:15, carb:28, fat:8, fiber:0, sugar:0, serving:1, unit:'ly', processed:0},
  {id:'rau_muong_luoc', name:'Rau muống Luộc', kcal:25, protein:2.7, carb:4, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'rau_muong_xao_toi_2', name:'Rau muống Xào tỏi', kcal:110, protein:3, carb:10, fat:7, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cai_thia_luoc', name:'Cải thìa Luộc', kcal:15, protein:1.5, carb:2, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cai_ngot_luoc', name:'Cải ngọt Luộc', kcal:20, protein:2, carb:3, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cai_xanh_luoc', name:'Cải xanh Luộc', kcal:22, protein:2, carb:4, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'rau_den_luoc', name:'Rau dền Luộc', kcal:23, protein:2.5, carb:4, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'mong_toi_luoc', name:'Mồng tơi Luộc', kcal:19, protein:2, carb:3, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bap_cai_luoc', name:'Bắp cải Luộc', kcal:25, protein:1.3, carb:6, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bap_cai_xao', name:'Bắp cải Xào', kcal:70, protein:2, carb:7, fat:4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cai_thao_luoc', name:'Cải thảo Luộc', kcal:16, protein:1.2, carb:3, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'xa_lach_song', name:'Xà lách Sống', kcal:15, protein:1.4, carb:3, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'rau_song_mixed', name:'Rau sống Mixed', kcal:20, protein:1.5, carb:4, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'rau_lang_luoc', name:'Rau lang Luộc', kcal:30, protein:2, carb:6, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_bap_luoc', name:'Đậu bắp Luộc', kcal:33, protein:2, carb:7, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bi_do_luoc', name:'Bí đỏ Luộc', kcal:34, protein:1, carb:8, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bi_xanh_luoc', name:'Bí xanh Luộc', kcal:13, protein:0.6, carb:3, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'su_su_luoc', name:'Su su Luộc', kcal:19, protein:0.8, carb:4, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_rot_luoc', name:'Cà rốt Luộc', kcal:41, protein:1, carb:10, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'khoai_tay_luoc', name:'Khoai tây Luộc', kcal:87, protein:2, carb:20, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'khoai_lang_luoc', name:'Khoai lang Luộc', kcal:86, protein:1.6, carb:20, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ngo_bap_luoc', name:'Ngô (bắp) Luộc', kcal:96, protein:3.4, carb:21, fat:1.5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cu_den_luoc', name:'Củ dền Luộc', kcal:43, protein:1.6, carb:10, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cu_cai_trang_luoc', name:'Củ cải trắng Luộc', kcal:18, protein:0.6, carb:4, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bong_cai_xanh_luoc', name:'Bông cải xanh Luộc', kcal:35, protein:2.8, carb:7, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bong_cai_xanh_xao', name:'Bông cải xanh Xào', kcal:80, protein:3, carb:8, fat:4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'sup_lo_trang_luoc', name:'Súp lơ trắng Luộc', kcal:25, protein:2, carb:5, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'mang_tay_luoc', name:'Măng tây Luộc', kcal:22, protein:2.4, carb:4, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_que_luoc', name:'Đậu que Luộc', kcal:31, protein:2, carb:7, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_ha_lan_luoc', name:'Đậu Hà Lan Luộc', kcal:84, protein:5, carb:15, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nam_kim_cham_luoc', name:'Nấm kim châm Luộc', kcal:37, protein:2.7, carb:7, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nam_dui_ga_ap_chao', name:'Nấm đùi gà Áp chảo', kcal:55, protein:3, carb:8, fat:2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nam_mo_luoc', name:'Nấm mỡ Luộc', kcal:22, protein:3, carb:3, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dua_leo_song', name:'Dưa leo Sống', kcal:15, protein:0.7, carb:4, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_chua_song', name:'Cà chua Sống', kcal:18, protein:0.9, carb:4, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_tim_nuong', name:'Cà tím Nướng', kcal:35, protein:1, carb:8, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_hu_trang', name:'Đậu hũ Trắng', kcal:76, protein:8, carb:2, fat:4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'salad_rau_khong_sot', name:'Salad rau Không sốt', kcal:80, protein:3, carb:12, fat:2, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'salad_rau_sot_me_rang', name:'Salad rau Sốt mè rang', kcal:220, protein:4, carb:15, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'trung_ga_luoc', name:'Trứng gà Luộc', kcal:78, protein:6, carb:0.6, fat:5, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trung_ga_op_la', name:'Trứng gà Ốp la', kcal:90, protein:6, carb:0.5, fat:7, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trung_vit_luoc', name:'Trứng vịt Luộc', kcal:130, protein:9, carb:1, fat:10, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trung_cut_luoc', name:'Trứng cút Luộc', kcal:17, protein:1.3, carb:0.1, fat:1.2, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'trung_cut_5_qua', name:'Trứng cút 5 quả', kcal:85, protein:7, carb:0.5, fat:6, fiber:0, sugar:0, serving:5, unit:'quả', processed:0},
  {id:'cha_lua_2', name:'Chả lụa', kcal:100, protein:6, carb:2, fat:7, fiber:0, sugar:0, serving:1, unit:'50g', processed:1},
  {id:'cha_bo', name:'Chả bò', kcal:110, protein:8, carb:2, fat:7, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'cha_ca_chien', name:'Chả cá Chiên', kcal:90, protein:7, carb:4, fat:5, fiber:0, sugar:0, serving:1, unit:'50g', processed:1},
  {id:'xuc_xich_duc_cp', name:'Xúc xích Đức/CP', kcal:140, protein:5, carb:2, fat:12, fiber:0, sugar:0, serving:1, unit:'cây', processed:1},
  {id:'thit_bo_them_pho_lau', name:'Thịt bò thêm Phở/lẩu', kcal:95, protein:11, carb:0, fat:5, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'gau_bo_them_pho_lau', name:'Gầu bò thêm Phở/lẩu', kcal:150, protein:9, carb:0, fat:12, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'gan_bo_them_pho_lau', name:'Gân bò thêm Phở/lẩu', kcal:80, protein:13, carb:0, fat:2, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'bo_vien_pho', name:'Bò viên Phở', kcal:40, protein:3, carb:1, fat:3, fiber:0, sugar:0, serving:1, unit:'viên', processed:0},
  {id:'tom_them_luoc_nuong', name:'Tôm thêm Luộc/nướng', kcal:60, protein:11, carb:0, fat:1, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'muc_them_luoc_nuong', name:'Mực thêm Luộc/nướng', kcal:70, protein:9, carb:1, fat:2, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'ga_xe_pho_chao', name:'Gà xé Phở/cháo', kcal:85, protein:14, carb:0, fat:3, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'da_ga_luoc_chien', name:'Da gà Luộc/chiên', kcal:135, protein:3, carb:0, fat:13, fiber:0, sugar:0, serving:1, unit:'30g', processed:1},
  {id:'heo_quay_them_50g', name:'Heo quay thêm 50g', kcal:175, protein:11, carb:0, fat:14, fiber:0, sugar:0, serving:1, unit:'50g', processed:1},
  {id:'thit_heo_luoc_50g', name:'Thịt heo luộc 50g', kcal:125, protein:10, carb:0, fat:9, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'xiu_mai_1_vien', name:'Xíu mại 1 viên', kcal:60, protein:4, carb:2, fat:4, fiber:0, sugar:0, serving:1, unit:'viên', processed:0},
  {id:'nem_chua_1_cai', name:'Nem chua 1 cái', kcal:65, protein:4, carb:2, fat:4, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'cha_gio_1_cuon', name:'Chả giò 1 cuốn', kcal:150, protein:5, carb:12, fat:8, fiber:0, sugar:0, serving:1, unit:'cuốn', processed:1},
  {id:'dau_hu_trang_2', name:'Đậu hũ Trắng', kcal:38, protein:4, carb:1, fat:2, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'dau_hu_chien_2', name:'Đậu hũ Chiên', kcal:100, protein:6, carb:4, fat:7, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'pho_mai_lat_cheddar', name:'Phô mai lát Cheddar', kcal:70, protein:4, carb:1, fat:6, fiber:0, sugar:0, serving:1, unit:'lát', processed:1},
  {id:'pho_mai_bao_mozzarella', name:'Phô mai bào Mozzarella', kcal:90, protein:7, carb:1, fat:7, fiber:0, sugar:0, serving:1, unit:'30g', processed:0},
  {id:'bo_mayonnaise', name:'Bơ Mayonnaise', kcal:100, protein:0, carb:1, fat:11, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'bo_thuc_vat_margarine', name:'Bơ thực vật Margarine', kcal:72, protein:0, carb:0, fat:8, fiber:0, sugar:0, serving:1, unit:'muỗng', processed:1},
  {id:'hanh_phi', name:'Hành phi', kcal:55, protein:1, carb:4, fat:4, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'top_mo', name:'Tóp mỡ', kcal:120, protein:2, carb:0, fat:12, fiber:0, sugar:0, serving:1, unit:'20g', processed:1},
  {id:'mo_hanh', name:'Mỡ hành', kcal:45, protein:0, carb:1, fat:5, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'sa_te', name:'Sa tế', kcal:70, protein:1, carb:2, fat:7, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'tuong_den_pho', name:'Tương đen Phở', kcal:35, protein:1, carb:8, fat:0, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'tuong_ot', name:'Tương ớt', kcal:20, protein:0, carb:5, fat:0, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'nuoc_mam_duong_pha', name:'Nước mắm đường Pha', kcal:25, protein:0, carb:6, fat:0, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'sot_me_rang_salad', name:'Sốt mè rang Salad', kcal:80, protein:1, carb:3, fat:7, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'sot_caesar_salad', name:'Sốt Caesar Salad', kcal:90, protein:1, carb:1, fat:9, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'ketchup_tuong_ca', name:'Ketchup Tương cà', kcal:20, protein:0, carb:5, fat:0, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:1},
  {id:'sot_pho_mai', name:'Sốt phô mai', kcal:110, protein:3, carb:4, fat:9, fiber:0, sugar:0, serving:1, unit:'30g', processed:1},
  {id:'quay_pho_chao', name:'Quẩy Phở/cháo', kcal:120, protein:2, carb:14, fat:6, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'banh_mi_them_1_2_o', name:'Bánh mì thêm 1/2 ổ', kcal:110, protein:4, carb:22, fat:1, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'bun_them_100g', name:'Bún thêm 100g', kcal:110, protein:2, carb:25, fat:0.5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'mi_them_100g', name:'Mì thêm 100g', kcal:140, protein:4, carb:28, fat:1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nui_them_100g', name:'Nui thêm 100g', kcal:130, protein:4, carb:26, fat:1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'com_trang_them_1_chen_nho', name:'Cơm trắng thêm 1 chén nhỏ', kcal:130, protein:2.5, carb:28, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'kimchi_han', name:'Kimchi Hàn', kcal:15, protein:1, carb:3, fat:0, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'rong_bien_kho', name:'Rong biển Khô', kcal:25, protein:1, carb:1, fat:2, fiber:0, sugar:0, serving:1, unit:'gói nhỏ', processed:0},
  {id:'bap_my_hat', name:'Bắp Mỹ Hạt', kcal:48, protein:2, carb:11, fat:1, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'nam_them_lau_nuong', name:'Nấm thêm Lẩu/nướng', kcal:18, protein:2, carb:3, fat:0, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'rau_song_them_mixed', name:'Rau sống thêm Mixed', kcal:10, protein:1, carb:2, fat:0, fiber:0, sugar:0, serving:1, unit:'50g', processed:0},
  {id:'dau_phong_rang', name:'Đậu phộng Rang', kcal:115, protein:5, carb:4, fat:10, fiber:0, sugar:0, serving:1, unit:'20g', processed:0},
  {id:'me_rang', name:'Mè rang', kcal:57, protein:2, carb:2, fat:5, fiber:0, sugar:0, serving:1, unit:'10g', processed:0},
  {id:'hanh_la', name:'Hành lá', kcal:3, protein:0.2, carb:0.7, fat:0, fiber:0, sugar:0, serving:1, unit:'10g', processed:0},
  {id:'toi_phi', name:'Tỏi phi', kcal:50, protein:1, carb:4, fat:4, fiber:0, sugar:0, serving:1, unit:'10g', processed:1},
  {id:'bo_dau_phong', name:'Bơ đậu phộng', kcal:95, protein:4, carb:3, fat:8, fiber:0, sugar:0, serving:1, unit:'muỗng canh', processed:0},
  {id:'whipping_cream', name:'Whipping cream', kcal:100, protein:1, carb:2, fat:10, fiber:0, sugar:0, serving:1, unit:'30ml', processed:1},
  {id:'hu_tieu_go_thap_cam', name:'Hủ tiếu gõ Thập cẩm', kcal:420, protein:20, carb:60, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bo_kho_banh_mi', name:'Bò kho Bánh mì', kcal:650, protein:32, carb:60, fat:28, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_mi_chao_day_du', name:'Bánh mì chảo Đầy đủ', kcal:700, protein:30, carb:50, fat:40, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_uot_long_ga', name:'Bánh ướt Lòng gà', kcal:450, protein:25, carb:50, fat:15, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'banh_hoi_heo_quay', name:'Bánh hỏi Heo quay', kcal:620, protein:28, carb:60, fat:28, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_can_trung_cut', name:'Bánh căn Trứng/cút', kcal:380, protein:16, carb:50, fat:12, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'bun_ca_chau_doc', name:'Bún cá Châu Đốc', kcal:480, protein:28, carb:58, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_ca_ro_dong_chuan', name:'Bún cá rô đồng Chuẩn', kcal:450, protein:26, carb:55, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'nui_xao_bo', name:'Nui xào Bò', kcal:620, protein:28, carb:75, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'mi_hoanh_thanh_xa_xiu', name:'Mì hoành thánh Xá xíu', kcal:520, protein:25, carb:65, fat:16, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_vit_tiem_chuan', name:'Mì vịt tiềm Chuẩn', kcal:650, protein:32, carb:70, fat:25, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'sup_cua_trung_cut', name:'Súp cua Trứng cút', kcal:180, protein:12, carb:22, fat:5, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'sup_ga_bap', name:'Súp gà Bắp', kcal:160, protein:12, carb:18, fat:4, fiber:0, sugar:0, serving:1, unit:'chén', processed:0},
  {id:'banh_da_cua_hai_phong', name:'Bánh đa cua Hải Phòng', kcal:550, protein:28, carb:65, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'banh_da_ca_hai_phong', name:'Bánh đa cá Hải Phòng', kcal:500, protein:30, carb:58, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_thang_ha_noi', name:'Bún thang Hà Nội', kcal:430, protein:26, carb:55, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_ngan_chuan', name:'Bún ngan Chuẩn', kcal:520, protein:28, carb:55, fat:18, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mien_ngan_chuan', name:'Miến ngan Chuẩn', kcal:480, protein:28, carb:50, fat:15, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'chao_vit_chuan', name:'Cháo vịt Chuẩn', kcal:420, protein:22, carb:48, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'chao_suon_quay', name:'Cháo sườn Quẩy', kcal:350, protein:12, carb:50, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'com_suon_trung', name:'Cơm sườn Trứng', kcal:750, protein:38, carb:82, fat:28, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_thit_kho', name:'Cơm Thịt kho', kcal:680, protein:28, carb:78, fat:24, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_ca_kho', name:'Cơm Cá kho', kcal:550, protein:30, carb:72, fat:15, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'com_ga_chien_mam', name:'Cơm Gà chiên mắm', kcal:780, protein:35, carb:75, fat:35, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_bo_luc_lac', name:'Cơm Bò lúc lắc', kcal:720, protein:35, carb:70, fat:28, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_bo_xao', name:'Cơm Bò xào', kcal:650, protein:32, carb:72, fat:20, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'com_chien_ca_man', name:'Cơm chiên Cá mặn', kcal:650, protein:22, carb:80, fat:24, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_trung_chien', name:'Cơm Trứng chiên', kcal:450, protein:15, carb:65, fat:12, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'com_ca_chien', name:'Cơm Cá chiên', kcal:620, protein:30, carb:70, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_dui_ga_nuong', name:'Cơm Đùi gà nướng', kcal:680, protein:35, carb:75, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'com_vit_quay', name:'Cơm Vịt quay', kcal:760, protein:32, carb:72, fat:35, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_xa_xiu', name:'Cơm Xá xíu', kcal:720, protein:32, carb:75, fat:28, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_heo_quay', name:'Cơm Heo quay', kcal:780, protein:32, carb:70, fat:38, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:1},
  {id:'com_cha_ca', name:'Cơm Chả cá', kcal:600, protein:28, carb:72, fat:18, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'com_ga_sot_tieu', name:'Cơm Gà sốt tiêu', kcal:680, protein:34, carb:72, fat:22, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'ca_vien_chien_chien', name:'Cá viên chiên Chiên', kcal:250, protein:10, carb:18, fat:15, fiber:0, sugar:0, serving:5, unit:'viên', processed:1},
  {id:'bo_vien_chien_chien', name:'Bò viên chiên Chiên', kcal:280, protein:14, carb:15, fat:18, fiber:0, sugar:0, serving:5, unit:'viên', processed:1},
  {id:'ho_lo_nuong_xuc_xich_mini', name:'Hồ lô nướng Xúc xích mini', kcal:180, protein:6, carb:8, fat:14, fiber:0, sugar:0, serving:1, unit:'cây', processed:1},
  {id:'xien_que_thap_cam', name:'Xiên que Thập cẩm', kcal:120, protein:5, carb:8, fat:8, fiber:0, sugar:0, serving:1, unit:'xiên', processed:1},
  {id:'xuc_xich_chien', name:'Xúc xích Chiên', kcal:180, protein:6, carb:5, fat:15, fiber:0, sugar:0, serving:1, unit:'cây', processed:1},
  {id:'khoai_tay_lac_pho_mai', name:'Khoai tây Lắc phô mai', kcal:420, protein:5, carb:52, fat:22, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'ga_ran_lac_pho_mai', name:'Gà rán Lắc phô mai', kcal:520, protein:28, carb:30, fat:30, fiber:0, sugar:0, serving:2, unit:'miếng', processed:1},
  {id:'pho_mai_que_chien', name:'Phô mai que Chiên', kcal:260, protein:10, carb:15, fat:18, fiber:0, sugar:0, serving:2, unit:'cây', processed:1},
  {id:'banh_gao_chien', name:'Bánh gạo Chiên', kcal:350, protein:6, carb:55, fat:12, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'trung_nuong_mo_hanh', name:'Trứng nướng Mỡ hành', kcal:180, protein:8, carb:8, fat:12, fiber:0, sugar:0, serving:1, unit:'chén', processed:1},
  {id:'banh_mi_nuong_muoi_ot', name:'Bánh mì nướng Muối ớt', kcal:320, protein:8, carb:42, fat:14, fiber:0, sugar:0, serving:1, unit:'ổ', processed:1},
  {id:'banh_trang_sa_te', name:'Bánh tráng Sa tế', kcal:280, protein:8, carb:42, fat:10, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_trang_me', name:'Bánh tráng Me', kcal:260, protein:6, carb:45, fat:8, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'ba_chi_heo_nuong', name:'Ba chỉ heo Nướng', kcal:380, protein:16, carb:2, fat:34, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'suon_heo_nuong', name:'Sườn heo Nướng', kcal:320, protein:22, carb:5, fat:24, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'bach_tuoc_nuong_sa_te', name:'Bạch tuộc Nướng sa tế', kcal:160, protein:25, carb:3, fat:5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'hau_nuong_mo_hanh', name:'Hàu Nướng mỡ hành', kcal:180, protein:12, carb:6, fat:12, fiber:0, sugar:0, serving:3, unit:'con', processed:0},
  {id:'hau_pho_mai', name:'Hàu Phô mai', kcal:260, protein:14, carb:6, fat:20, fiber:0, sugar:0, serving:3, unit:'con', processed:1},
  {id:'ech_nuong', name:'Ếch Nướng', kcal:140, protein:20, carb:2, fat:5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'long_heo_nuong', name:'Lòng heo Nướng', kcal:260, protein:15, carb:2, fat:20, fiber:0, sugar:0, serving:1, unit:'100g', processed:1},
  {id:'be_thui_cuon_banh_trang', name:'Bê thui Cuốn bánh tráng', kcal:450, protein:35, carb:28, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'de_nuong', name:'Dê Nướng', kcal:190, protein:25, carb:2, fat:9, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bo_la_lot_nuong', name:'Bò lá lốt Nướng', kcal:320, protein:22, carb:8, fat:22, fiber:0, sugar:0, serving:5, unit:'cuốn', processed:0},
  {id:'chan_ga_nuong', name:'Chân gà Nướng', kcal:280, protein:20, carb:8, fat:18, fiber:0, sugar:0, serving:2, unit:'cái', processed:1},
  {id:'gan_bo_nuong', name:'Gân bò Nướng', kcal:170, protein:28, carb:2, fat:5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'coc_chua', name:'Cóc Chua', kcal:44, protein:1, carb:11, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'man_ha_noi', name:'Mận Hà Nội', kcal:46, protein:0.7, carb:11, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'sapoche_chin', name:'Sapoche Chín', kcal:83, protein:0.4, carb:20, fat:1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'na_mang_cau_ta', name:'Na Mãng cầu ta', kcal:94, protein:2, carb:23, fat:0.5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'mang_cau_xiem_chin', name:'Mãng cầu xiêm Chín', kcal:66, protein:1, carb:17, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dua_non_com_dua', name:'Dừa non Cơm dừa', kcal:140, protein:1.5, carb:6, fat:13, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'kiwi_xanh', name:'Kiwi Xanh', kcal:61, protein:1.1, carb:15, fat:0.5, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'viet_quat_tuoi', name:'Việt quất Tươi', kcal:57, protein:0.7, carb:14, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cherry_tuoi', name:'Cherry Tươi', kcal:63, protein:1, carb:16, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'le_chau_a', name:'Lê Châu Á', kcal:42, protein:0.5, carb:11, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'coca_cola_zero', name:'Coca-Cola Zero', kcal:0, protein:0, carb:0, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:0},
  {id:'pepsi_black', name:'Pepsi Black', kcal:0, protein:0, carb:0, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:0},
  {id:'sprite_chuan', name:'Sprite Chuẩn', kcal:140, protein:0, carb:35, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'fanta_cam', name:'Fanta Cam', kcal:150, protein:0, carb:38, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'mirinda_cam', name:'Mirinda Cam', kcal:155, protein:0, carb:39, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'c2_tra_xanh', name:'C2 Trà xanh', kcal:90, protein:0, carb:22, fat:0, fiber:0, sugar:0, serving:1, unit:'Chai 360ml', processed:1},
  {id:'khong_do_tra_xanh', name:'Không Độ Trà xanh', kcal:85, protein:0, carb:21, fat:0, fiber:0, sugar:0, serving:1, unit:'Chai 455ml', processed:1},
  {id:'oolong_tea_khong_duong', name:'Oolong Tea+ Không đường', kcal:0, protein:0, carb:0, fat:0, fiber:0, sugar:0, serving:1, unit:'Chai 455ml', processed:0},
  {id:'sting_gold', name:'Sting Gold', kcal:170, protein:0, carb:42, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'warrior_energy_drink', name:'Warrior Energy Drink', kcal:160, protein:0, carb:40, fat:0, fiber:0, sugar:0, serving:1, unit:'Lon 330ml', processed:1},
  {id:'number_1_energy_drink', name:'Number 1 Energy Drink', kcal:150, protein:0, carb:37, fat:0, fiber:0, sugar:0, serving:1, unit:'Chai 330ml', processed:1},
  {id:'milo_hop', name:'Milo Hộp', kcal:140, protein:4, carb:22, fat:4, fiber:0, sugar:0, serving:1, unit:'180ml', processed:0},
  {id:'ensure_original', name:'Ensure Original', kcal:230, protein:9, carb:34, fat:6, fiber:0, sugar:0, serving:1, unit:'220ml', processed:0},
  {id:'mi_goi_hao_hao_tom_chua_cay', name:'Mì gói Hảo Hảo tôm chua cay', kcal:350, protein:7, carb:49, fat:14, fiber:0, sugar:0, serving:1, unit:'gói', processed:1},
  {id:'mi_goi_omachi_bo_ham', name:'Mì gói Omachi bò hầm', kcal:380, protein:8, carb:52, fat:16, fiber:0, sugar:0, serving:1, unit:'gói', processed:1},
  {id:'mi_goi_indomie_mi_goreng', name:'Mì gói Indomie Mi Goreng', kcal:390, protein:8, carb:52, fat:17, fiber:0, sugar:0, serving:1, unit:'gói', processed:1},
  {id:'banh_oreo', name:'Bánh Oreo', kcal:160, protein:2, carb:25, fat:7, fiber:0, sugar:0, serving:3, unit:'cái', processed:1},
  {id:'banh_chocopie', name:'Bánh Chocopie', kcal:170, protein:2, carb:28, fat:6, fiber:0, sugar:0, serving:1, unit:'cái', processed:1},
  {id:'chocolate_snickers', name:'Chocolate Snickers', kcal:250, protein:4, carb:33, fat:12, fiber:0, sugar:0, serving:1, unit:'thanh', processed:1},
  {id:'banh_mi_cha_ca_da_nang', name:'Bánh mì chả cá Đà Nẵng', kcal:420, protein:20, carb:48, fat:14, fiber:0, sugar:0, serving:1, unit:'ổ', processed:0},
  {id:'bun_nem_nuong_nha_trang', name:'Bún nem nướng Nha Trang', kcal:580, protein:28, carb:68, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'com_ga_xe_tam_ky', name:'Cơm gà xé Tam Kỳ', kcal:580, protein:32, carb:75, fat:14, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'bun_cua_mien_tay', name:'Bún cua Miền Tây', kcal:500, protein:24, carb:62, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_quang_ech_quang_nam', name:'Mì quảng ếch Quảng Nam', kcal:620, protein:32, carb:60, fat:22, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'bun_nuoc_leo_soc_trang', name:'Bún nước lèo Sóc Trăng', kcal:520, protein:26, carb:68, fat:14, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_sua_nha_trang', name:'Bún sứa Nha Trang', kcal:430, protein:28, carb:55, fat:8, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'bun_ken_phu_quoc', name:'Bún kèn Phú Quốc', kcal:500, protein:24, carb:60, fat:16, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'hu_tieu_sa_te_bo', name:'Hủ tiếu sa tế Bò', kcal:620, protein:30, carb:65, fat:22, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'pha_lau_banh_mi', name:'Phá lấu Bánh mì', kcal:550, protein:22, carb:40, fat:30, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'banh_mi_pha_lau_sai_gon', name:'Bánh mì phá lấu Sài Gòn', kcal:520, protein:20, carb:52, fat:24, fiber:0, sugar:0, serving:1, unit:'ổ', processed:1},
  {id:'banh_mi_que_hai_phong', name:'Bánh mì que Hải Phòng', kcal:220, protein:8, carb:30, fat:8, fiber:0, sugar:0, serving:1, unit:'ổ', processed:0},
  {id:'com_nieu_ca_kho', name:'Cơm niêu Cá kho', kcal:650, protein:30, carb:82, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'com_chay_kho_quet', name:'Cơm cháy Kho quẹt', kcal:580, protein:14, carb:72, fat:24, fiber:0, sugar:0, serving:1, unit:'phần', processed:1},
  {id:'lau_bo_nhung_giam', name:'Lẩu bò Nhúng giấm', kcal:580, protein:38, carb:40, fat:18, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'lau_de_chuan', name:'Lẩu dê Chuẩn', kcal:620, protein:40, carb:38, fat:24, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'banh_dap_quang_nam', name:'Bánh đập Quảng Nam', kcal:350, protein:10, carb:58, fat:8, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'banh_uot_thit_nuong', name:'Bánh ướt Thịt nướng', kcal:520, protein:26, carb:60, fat:16, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'bun_thai_hai_san', name:'Bún thái Hải sản', kcal:480, protein:26, carb:62, fat:10, fiber:0, sugar:0, serving:1, unit:'tô', processed:0},
  {id:'mi_cay_hai_san', name:'Mì cay Hải sản', kcal:600, protein:30, carb:72, fat:20, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'com_am_phu_hue', name:'Cơm âm phủ Huế', kcal:620, protein:28, carb:78, fat:18, fiber:0, sugar:0, serving:1, unit:'dĩa', processed:0},
  {id:'banh_mi_ga_xe', name:'Bánh mì Gà xé', kcal:430, protein:24, carb:50, fat:12, fiber:0, sugar:0, serving:1, unit:'ổ', processed:0},
  {id:'bun_thit_nuong_cha_gio', name:'Bún thịt nướng Chả giò', kcal:650, protein:30, carb:70, fat:22, fiber:0, sugar:0, serving:1, unit:'tô', processed:1},
  {id:'goi_ga_bap_cai', name:'Gỏi gà Bắp cải', kcal:280, protein:28, carb:12, fat:8, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'goi_ngo_sen_tom_thit', name:'Gỏi ngó sen Tôm thịt', kcal:260, protein:18, carb:18, fat:8, fiber:0, sugar:0, serving:1, unit:'phần', processed:0},
  {id:'bia_larue_tiger_lon_tieu_chu', name:'Bia Larue / Tiger Lon tiêu chuẩn', kcal:140, protein:1.1, carb:11, fat:0, fiber:0, sugar:0, serving:1, unit:'330ml', processed:1},
  {id:'bia_craft_ipa_ly_tieu_chuan', name:'Bia Craft (IPA) Ly tiêu chuẩn', kcal:200, protein:2, carb:18, fat:0, fiber:0, sugar:0, serving:1, unit:'330ml', processed:1},
  {id:'ruou_vang_do_ly_thuy_tinh', name:'Rượu vang đỏ Ly thủy tinh', kcal:125, protein:0.1, carb:3.8, fat:0, fiber:0, sugar:0, serving:1, unit:'150ml', processed:0},
  {id:'ruou_vang_trang_ly_thuy_tinh', name:'Rượu vang trắng Ly thủy tinh', kcal:120, protein:0.1, carb:3, fat:0, fiber:0, sugar:0, serving:1, unit:'150ml', processed:0},
  {id:'ruou_soju_chai_truyen_thong', name:'Rượu Soju Chai truyền thống', kcal:400, protein:0, carb:8, fat:0, fiber:0, sugar:0, serving:1, unit:'360ml', processed:1},
  {id:'ruou_whisky_vodka_shot_don', name:'Rượu Whisky / Vodka Shot đơn', kcal:100, protein:0, carb:0, fat:0, fiber:0, sugar:0, serving:1, unit:'45ml', processed:1},
  {id:'uc_ga_hap_ap_chao_khong_dau', name:'Ức gà Hấp/Áp chảo không dầu', kcal:165, protein:31, carb:0, fat:3.6, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'than_bo_nuong_ap_chao', name:'Thăn bò Nướng/Áp chảo', kcal:250, protein:26, carb:0, fat:15, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_hoi_phi_le_tuoi', name:'Cá hồi Phi lê tươi', kcal:208, protein:20, carb:0, fat:13, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'trung_ga_luoc_chin', name:'Trứng gà Luộc chín', kcal:78, protein:6.3, carb:0.6, fat:5.3, fiber:0, sugar:0, serving:1, unit:'quả', processed:0},
  {id:'dau_hu_tuoi_luoc', name:'Đậu hũ Tươi/Luộc', kcal:76, protein:8, carb:1.9, fat:4.8, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'khoai_lang_luoc_hap', name:'Khoai lang Luộc/Hấp', kcal:86, protein:1.6, carb:20.1, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'gao_lut_com_nau_chin', name:'Gạo lứt Cơm nấu chín', kcal:110, protein:2.6, carb:23, fat:0.9, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'yen_mach_can_vo_nguyen_hat', name:'Yến mạch Cán vỡ/Nguyên hạt', kcal:389, protein:16.9, carb:66.3, fat:6.9, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'hat_hanh_nhan_say_kho_nguyen', name:'Hạt hạnh nhân Sấy khô nguyên vị', kcal:579, protein:21, carb:22, fat:50, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'sua_chua_hy_lap_khong_duong', name:'Sữa chua Hy Lạp Không đường', kcal:59, protein:10, carb:3.6, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bong_cai_xanh_sup_lo_luoc_ha', name:'Bông cải xanh (Súp lơ) Luộc/Hấp', kcal:34, protein:2.8, carb:7, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cai_bo_xoi_rau_chan_vit_tuoi', name:'Cải bó xôi (Rau chân vịt) Tươi sống', kcal:23, protein:2.9, carb:3.6, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'xa_lach_tuoi_song', name:'Xà lách Tươi sống', kcal:15, protein:1.4, carb:2.9, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_rot_luoc_hap', name:'Cà rốt Luộc/Hấp', kcal:41, protein:0.9, carb:9.6, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'ca_chua_tuoi_chin_do', name:'Cà chua Tươi chín đỏ', kcal:18, protein:0.9, carb:3.9, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dua_leo_dua_chuot_tuoi_song_', name:'Dưa leo (Dưa chuột) Tươi sống nguyên vỏ', kcal:15, protein:0.7, carb:3.6, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bi_ngoi_luoc_hap', name:'Bí ngòi Luộc/Hấp', kcal:17, protein:1.2, carb:3.1, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'mang_tay_nuong_ap_chao_nhe', name:'Măng tây Nướng áp chảo nhẹ', kcal:20, protein:2.2, carb:3.9, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'nam_dui_ga_luoc_xao_moc', name:'Nấm đùi gà Luộc/Xào mộc', kcal:35, protein:3.1, carb:5.5, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'bo_tuoi_nguyen_chat', name:'Bơ Tươi nguyên chất', kcal:160, protein:2, carb:8.5, fat:15, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'chuoi_gia_trai_chin', name:'Chuối già Trái chín', kcal:89, protein:1.1, carb:22.8, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'tao_tay_nguyen_vo', name:'Táo tây Nguyên vỏ', kcal:52, protein:0.3, carb:13.8, fat:0.2, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'buoi_da_xanh_mui_tuoi', name:'Bưởi da xanh Múi tươi', kcal:38, protein:0.8, carb:9.6, fat:0, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'oi_bo_hat_an_ca_vo', name:'Ổi Bỏ hạt/Ăn cả vỏ', kcal:68, protein:2.6, carb:14.3, fat:1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'dau_tay_qua_tuoi_chin', name:'Dâu tây Quả tươi chín', kcal:32, protein:0.7, carb:7.7, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'viet_quat_qua_tuoi', name:'Việt quất Quả tươi', kcal:57, protein:0.7, carb:14.5, fat:0.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'cam_mui_tuoi', name:'Cam Múi tươi', kcal:47, protein:0.9, carb:11.8, fat:0.1, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'xoai_chin_ma_xoai_tuoi', name:'Xoài chín Má xoài tươi', kcal:60, protein:0.8, carb:15, fat:0.4, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'sau_rieng_com_thit_tuoi', name:'Sầu riêng Cơm thịt tươi', kcal:147, protein:1.5, carb:27.1, fat:5.3, fiber:0, sugar:0, serving:1, unit:'100g', processed:0},
  {id:'tiec_cuoi_nhe', name:'Tiệc cưới Nhẹ', kcal:1400, protein:70, carb:105, fat:70, fiber:0, sugar:0, serving:1, unit:'lần', processed:0},
  {id:'tiec_cuoi_binh_thuong', name:'Tiệc cưới Bình thường', kcal:2000, protein:100, carb:150, fat:100, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'tiec_cuoi_nhieu', name:'Tiệc cưới Nhiều', kcal:2600, protein:130, carb:195, fat:130, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'tiec_cuoi_rat_nhieu', name:'Tiệc cưới Rất nhiều', kcal:3400, protein:170, carb:255, fat:170, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'tiec_cong_ty_binh_thuong', name:'Tiệc công ty Bình thường', kcal:2200, protein:110, carb:170, fat:110, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'buffet_trua_binh_thuong', name:'Buffet trưa Bình thường', kcal:1200, protein:60, carb:110, fat:55, fiber:0, sugar:0, serving:1, unit:'lần', processed:0},
  {id:'buffet_toi_binh_thuong', name:'Buffet tối Bình thường', kcal:1800, protein:90, carb:150, fat:90, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'bbq_nuong_binh_thuong', name:'BBQ/Nướng Bình thường', kcal:2000, protein:130, carb:80, fat:120, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'lau_binh_thuong', name:'Lẩu Bình thường', kcal:1500, protein:90, carb:100, fat:70, fiber:0, sugar:0, serving:1, unit:'lần', processed:0},
  {id:'sinh_nhat_nha_hang_binh_thuo', name:'Sinh nhật nhà hàng Bình thường', kcal:1500, protein:70, carb:130, fat:70, fiber:0, sugar:0, serving:1, unit:'lần', processed:0},
  {id:'nhau_bia_nhe_binh_thuong', name:'Nhậu bia nhẹ Bình thường', kcal:1800, protein:90, carb:130, fat:90, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'nhau_bia_nhieu_binh_thuong', name:'Nhậu bia nhiều Bình thường', kcal:3000, protein:150, carb:220, fat:150, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'tra_sua_an_vat_binh_thuong', name:'Trà sữa + ăn vặt Bình thường', kcal:800, protein:15, carb:110, fat:30, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'xem_phim_bap_nuoc_binh_thuon', name:'Xem phim + bắp nước Bình thường', kcal:1000, protein:12, carb:150, fat:35, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'tiec_tat_nien_binh_thuong', name:'Tiệc tất niên Bình thường', kcal:2500, protein:120, carb:180, fat:130, fiber:0, sugar:0, serving:1, unit:'lần', processed:1},
  {id:'du_lich_1_ngay', name:'Du lịch 1 ngày', kcal:2500, protein:100, carb:250, fat:100, fiber:0, sugar:0, serving:1, unit:'ngày', processed:0},
  {id:'tet_nguyen_dan_1_ngay', name:'Tết Nguyên Đán 1 ngày', kcal:3000, protein:120, carb:300, fat:130, fiber:0, sugar:0, serving:1, unit:'ngày', processed:1}
];

function _noTone(s) {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D').toLowerCase();
}

function searchFood(q) {
  if (!q) return FOOD_DB.slice(0, 14);
  const k = _noTone(q.trim());
  return FOOD_DB.filter(f => _noTone(f.name).includes(k)).slice(0, 14);
}

function getFood(id) { return FOOD_DB.find(f => f.id === id) || null; }

if (typeof window !== 'undefined') { window.FOOD_DB = FOOD_DB; window.searchFood = searchFood; window.getFood = getFood; }
if (typeof module !== 'undefined' && module.exports) module.exports = { FOOD_DB, searchFood, getFood };
